///drawShips()
draw_set_color(c_white);
draw_set_font(font_gamefont);
draw_set_halign(fa_left);
var shipName = "Please select a ship.";
if (obj_shipsmenu.selected == 1) var shipName = getShipString(0, 0);
if (obj_shipsmenu.selected == 2 && shopCheck(SHIPS, 0)) var shipName = getShipString(0, 1);
draw_text(10, 10, shipName);
var shipSprite = -1;
if (obj_shipsmenu.selected == 1) var shipSprite = spr_redship1;
if (obj_shipsmenu.selected == 2 && shopCheck(SHIPS, 0)) var shipSprite = spr_shooterplayer;
shader_set(shader_paletteswap);
var pSSampler = shader_get_sampler_index(shader_paletteswap, "Palette");
var palettes = background_get_texture(bg_shippalettes);
texture_set_stage(pSSampler, palettes);
shader_set_uniform_f(shader_get_uniform(shader_paletteswap, "offset"), SAVE_MAP[? "Color"]/256);
if (shipSprite != -1) draw_sprite_ext(shipSprite, 0, 20 + sprite_get_width(shipSprite), room_height/2, 2, 2, 0, c_white, 1);
shader_reset();
draw_set_font(font_menufont);
draw_set_halign(fa_left);
var shipDesc = "";
if (obj_shipsmenu.selected == 1) var shipDesc = getShipString(2, 0);
if (obj_shipsmenu.selected == 2 && shopCheck(SHIPS, 0)) var shipDesc = getShipString(2, 1);
draw_text(20, 160, shipDesc);
var special = "";
if (obj_shipsmenu.selected == 1) var special = getShipString(3, 0);
if (obj_shipsmenu.selected == 2 && shopCheck(SHIPS, 0)) var special = getShipString(3, 1);
draw_text(10, 30, special);
var specialDesc = "";
if (obj_shipsmenu.selected == 1) var specialDesc = getShipString(4, 0);
if (obj_shipsmenu.selected == 2 && shopCheck(SHIPS, 0)) var specialDesc = getShipString(4, 1);
draw_text(10, 40, specialDesc);
